version: "3.8"

services:

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    networks:
      - hospital-network

  backend:
    image: gi777/hospital-backend:latest
    ports:
      - "7000:7000"
    environment:
      MONGO_URI: mongodb://mongo:27017/hospitaldb
      PORT: 7000
    networks:
      - hospital-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: gi777/hospital-frontend:latest
    ports:
      - "6000:80"
    networks:
      - hospital-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  hospital-network:
    driver: overlay

volumes:
  mongo_data:
